<?php

declare(strict_types=1);

namespace App\Twig;

use App\Twig\Admin as AdminRuntime;
use App\Twig\Content as ContentRuntime;
use App\Twig\Content\BreadcrumbRuntime;
use App\Twig\Core as CoreRuntime;
use App\Twig\Translation as TranslationRuntime;
use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;

/**
 * CoreExtension.
 *
 * @author Sébastien FOURNIER <fournier.sebastien@outlook.com>
 */
class CoreExtension extends AbstractExtension
{
    public function getFilters(): array
    {
        /** Admin */
        $adminFilters = [
            new TwigFilter('symfonyVersion', [AdminRuntime\CoreRuntime::class, 'symfonyVersion']),
            new TwigFilter('phpversion', [AdminRuntime\CoreRuntime::class, 'phpversion']),
            new TwigFilter('blockTypesActionsGroups', [AdminRuntime\CoreRuntime::class, 'blockTypesActionsGroups']),
            new TwigFilter('indexAllowed', [AdminRuntime\CoreRuntime::class, 'indexAllowed']),
            new TwigFilter('seasonIcon', [AdminRuntime\CoreRuntime::class, 'seasonIcon']),
            new TwigFilter('logAlert', [AdminRuntime\CoreRuntime::class, 'logAlert']),
            new TwigFilter('methodInit', [AdminRuntime\CoreRuntime::class, 'methodInit']),
            new TwigFilter('buttonChecker', [AdminRuntime\CoreRuntime::class, 'buttonChecker']),
            new TwigFilter('buttonRoleChecker', [AdminRuntime\CoreRuntime::class, 'buttonRoleChecker']),
            new TwigFilter('blockFeatureName', [AdminRuntime\CoreRuntime::class, 'blockFeatureName']),
            new TwigFilter('blockTypesActive', [AdminRuntime\CoreRuntime::class, 'blockTypesActive']),
        ];

        /** Content */
        $contentFilters = [
            new TwigFilter('breadcrumb', [BreadcrumbRuntime::class, 'breadcrumb']),
            new TwigFilter('indexPage', [BreadcrumbRuntime::class, 'indexPage']),
            new TwigFilter('browser', [ContentRuntime\BrowserRuntime::class, 'browser']),
            new TwigFilter('screen', [ContentRuntime\BrowserRuntime::class, 'screen']),
            new TwigFilter('isDesktop', [ContentRuntime\BrowserRuntime::class, 'isDesktop']),
            new TwigFilter('isTablet', [ContentRuntime\BrowserRuntime::class, 'isTablet']),
            new TwigFilter('isMobile', [ContentRuntime\BrowserRuntime::class, 'isMobile']),
            new TwigFilter('isFirefox', [ContentRuntime\BrowserRuntime::class, 'isFirefox']),
            new TwigFilter('isChrome', [ContentRuntime\BrowserRuntime::class, 'isChrome']),
            new TwigFilter('isSafari', [ContentRuntime\BrowserRuntime::class, 'isSafari']),
            new TwigFilter('isEdge', [ContentRuntime\BrowserRuntime::class, 'isEdge']),
            new TwigFilter('isIE', [ContentRuntime\BrowserRuntime::class, 'isIE']),
            new TwigFilter('isOpera', [ContentRuntime\BrowserRuntime::class, 'isOpera']),
            new TwigFilter('productData', [ContentRuntime\CatalogRuntime::class, 'productData']),
            new TwigFilter('allCatalogCategories', [ContentRuntime\CatalogRuntime::class, 'allCatalogCategories']),
            new TwigFilter('productInCart', [ContentRuntime\CatalogRuntime::class, 'productInCart']),
            new TwigFilter('productsInCart', [ContentRuntime\CatalogRuntime::class, 'productsInCart']),
            new TwigFilter('valueProductBySlugAndProduct', [ContentRuntime\CatalogRuntime::class, 'valueProductBySlugAndProduct']),
            new TwigFilter('colors', [ContentRuntime\ColorRuntime::class, 'colors']),
            new TwigFilter('color', [ContentRuntime\ColorRuntime::class, 'color']),
            new TwigFilter('newZone', [ContentRuntime\ComponentRuntime::class, 'newZone']),
            new TwigFilter('newBlock', [ContentRuntime\ComponentRuntime::class, 'newBlock']),
            new TwigFilter('isComponentUser', [ContentRuntime\ComponentRuntime::class, 'isComponentUser']),
            new TwigFilter('lastRoute', [ContentRuntime\CoreRuntime::class, 'lastRoute']),
            new TwigFilter('email', [ContentRuntime\CoreRuntime::class, 'email']),
            new TwigFilter('jsonDecode', [ContentRuntime\CoreRuntime::class, 'jsonDecode']),
            new TwigFilter('phone', [ContentRuntime\CoreRuntime::class, 'phone']),
            new TwigFilter('address', [ContentRuntime\CoreRuntime::class, 'address']),
            new TwigFilter('mailToBody', [ContentRuntime\CoreRuntime::class, 'mailToBody']),
            new TwigFilter('urlize', [ContentRuntime\CoreRuntime::class, 'urlize']),
            new TwigFilter('removeHtmlAttrs', [ContentRuntime\CoreRuntime::class, 'removeHtmlAttrs']),
            new TwigFilter('encrypt', [ContentRuntime\CoreRuntime::class, 'encrypt']),
            new TwigFilter('decrypt', [ContentRuntime\CoreRuntime::class, 'decrypt']),
            new TwigFilter('uriInfos', [ContentRuntime\CoreRuntime::class, 'uriInfos']),
            new TwigFilter('truncate', [ContentRuntime\CoreRuntime::class, 'truncate']),
            new TwigFilter('centimeterToMeter', [ContentRuntime\CoreRuntime::class, 'centimeterToMeter']),
            new TwigFilter('minutesToHour', [ContentRuntime\CoreRuntime::class, 'minutesToHour']),
            new TwigFilter('firstIsVowel', [ContentRuntime\CoreRuntime::class, 'firstIsVowel']),
            new TwigFilter('htmlEntities', [ContentRuntime\CoreRuntime::class, 'htmlEntities']),
            new TwigFilter('intVal', [ContentRuntime\CoreRuntime::class, 'intVal']),
            new TwigFilter('shuffle', [ContentRuntime\CoreRuntime::class, 'shuffle']),
            new TwigFilter('fileInfo', [ContentRuntime\FileRuntime::class, 'fileInfo']),
            new TwigFilter('formatBytes', [ContentRuntime\FileRuntime::class, 'formatBytes']),
            new TwigFilter('convertToBytesSize', [ContentRuntime\FileRuntime::class, 'convertToBytesSize']),
            new TwigFilter('fileExist', [ContentRuntime\FileRuntime::class, 'fileExist']),
            new TwigFilter('jsRouting', [ContentRuntime\FileRuntime::class, 'jsRouting']),
            new TwigFilter('asGoogleFont', [ContentRuntime\FontsRuntime::class, 'asGoogleFont']),
            new TwigFilter('appAdminFonts', [ContentRuntime\FontsRuntime::class, 'appAdminFonts']),
            new TwigFilter('contactValues', [ContentRuntime\FormRuntime::class, 'contactValues']),
            new TwigFilter('indexGalleryCategories', [ContentRuntime\FormRuntime::class, 'indexGalleryCategories']),
            new TwigFilter('indexGalleryMedias', [ContentRuntime\FormRuntime::class, 'indexGalleryMedias']),
            new TwigFilter('cookies', [ContentRuntime\GdprRuntime::class, 'cookies']),
            new TwigFilter('cookie', [ContentRuntime\GdprRuntime::class, 'cookie']),
            new TwigFilter('iframe', [ContentRuntime\GdprRuntime::class, 'iframe']),
            new TwigFilter('addThis', [ContentRuntime\GdprRuntime::class, 'addThis']),
            new TwigFilter('tawkTo', [ContentRuntime\GdprRuntime::class, 'tawkTo']),
            new TwigFilter('gdprArguments', [ContentRuntime\GdprRuntime::class, 'gdprArguments']),
            new TwigFilter('markdown', [ContentRuntime\MarkdownRuntime::class, 'markdown']),
            new TwigFilter('extractMarkdownH1', [ContentRuntime\MarkdownRuntime::class, 'extractMarkdownH1']),
            new TwigFilter('icon', [ContentRuntime\IconRuntime::class, 'icon']),
            new TwigFilter('layoutRelations', [ContentRuntime\LayoutRuntime::class, 'layoutRelations']),
            new TwigFilter('cacheKey', [ContentRuntime\LayoutRuntime::class, 'cacheKey']),
            new TwigFilter('styleClass', [ContentRuntime\LayoutRuntime::class, 'styleClass']),
            new TwigFilter('renderBlock', [ContentRuntime\LayoutRuntime::class, 'renderBlock']),
            new TwigFilter('bodyClasses', [ContentRuntime\LayoutRuntime::class, 'bodyClasses']),
            new TwigFilter('zoneClasses', [ContentRuntime\LayoutRuntime::class, 'zoneClasses']),
            new TwigFilter('colClasses', [ContentRuntime\LayoutRuntime::class, 'colClasses']),
            new TwigFilter('blockClasses', [ContentRuntime\LayoutRuntime::class, 'blockClasses']),
            new TwigFilter('blockAlignment', [ContentRuntime\LayoutRuntime::class, 'blockAlignment']),
            new TwigFilter('elementOrders', [ContentRuntime\LayoutRuntime::class, 'elementOrders']),
            new TwigFilter('margins', [ContentRuntime\LayoutRuntime::class, 'margins']),
            new TwigFilter('paddings', [ContentRuntime\LayoutRuntime::class, 'paddings']),
            new TwigFilter('effectsAttrs', [ContentRuntime\LayoutRuntime::class, 'effectsAttrs']),
            new TwigFilter('mediasSizes', [ContentRuntime\LayoutRuntime::class, 'mediasSizes']),
            new TwigFilter('mainLayoutTitle', [ContentRuntime\LayoutRuntime::class, 'mainLayoutTitle']),
            new TwigFilter('layoutBlockType', [ContentRuntime\LayoutRuntime::class, 'layoutBlockType']),
            new TwigFilter('transitionsAttributes', [ContentRuntime\LayoutRuntime::class, 'transitionsAttributes']),
            new TwigFilter('transitionAttributes', [ContentRuntime\LayoutRuntime::class, 'transitionAttributes']),
            new TwigFilter('manifest', [ContentRuntime\ManifestRuntime::class, 'manifest']),
            new TwigFilter('mapPointsGroupByCategories', [ContentRuntime\MapRuntime::class, 'mapPointsGroupByCategories']),
            new TwigFilter('fonts', [ContentRuntime\MediaRuntime::class, 'fonts']),
            new TwigFilter('mediasSize', [ContentRuntime\MediaRuntime::class, 'mediasSize']),
            new TwigFilter('haveMainMedia', [ContentRuntime\MediaRuntime::class, 'haveMainMedia']),
            new TwigFilter('mainMedia', [ContentRuntime\MediaRuntime::class, 'mainMedia']),
            new TwigFilter('mediasIdsByPosition', [ContentRuntime\MediaRuntime::class, 'mediasIdsByPosition']),
            new TwigFilter('mediasByCategories', [ContentRuntime\MediaRuntime::class, 'mediasByCategories']),
            new TwigFilter('mediasWithFilename', [ContentRuntime\MediaRuntime::class, 'mediasWithFilename']),
            new TwigFilter('imgIsWhite', [ContentRuntime\MediaRuntime::class, 'imgIsWhite']),
            new TwigFilter('subNavigation', [ContentRuntime\MenuRuntime::class, 'subNavigation']),
            new TwigFilter('zonesNavigation', [ContentRuntime\MenuRuntime::class, 'zonesNavigation']),
            new TwigFilter('seo', [ContentRuntime\SeoRuntime::class, 'seo']),
            new TwigFilter('table', [ContentRuntime\TableRuntime::class, 'table']),
            new TwigFilter('fileIcon', [ContentRuntime\ThumbnailRuntime::class, 'fileIcon']),
            new TwigFilter('file', [ContentRuntime\ThumbnailRuntime::class, 'file']),
            new TwigFilter('thumb', [ContentRuntime\ThumbnailRuntime::class, 'thumb']),
            new TwigFilter('imgFilter', [ContentRuntime\ThumbnailRuntime::class, 'imgFilter']),
            new TwigFilter('mediaThumbs', [ContentRuntime\ThumbnailRuntime::class, 'mediaThumbs']),
            new TwigFilter('video', [ContentRuntime\VideoRuntime::class, 'video']),
        ];

        /** Core */
        $coreFilters = [
            new TwigFilter('routeArgs', [CoreRuntime\AppRuntime::class, 'routeArgs']),
            new TwigFilter('find', [CoreRuntime\AppRuntime::class, 'find']),
            new TwigFilter('isDebug', [CoreRuntime\AppRuntime::class, 'isDebug']),
            new TwigFilter('routeExist', [CoreRuntime\AppRuntime::class, 'routeExist']),
            new TwigFilter('routeName', [CoreRuntime\AppRuntime::class, 'routeName']),
            new TwigFilter('getClass', [CoreRuntime\AppRuntime::class, 'getClass']),
            new TwigFilter('instanceof', [CoreRuntime\AppRuntime::class, 'instanceof']),
            new TwigFilter('isObject', [CoreRuntime\AppRuntime::class, 'isObject']),
            new TwigFilter('isArray', [CoreRuntime\AppRuntime::class, 'isArray']),
            new TwigFilter('isBool', [CoreRuntime\AppRuntime::class, 'isBool']),
            new TwigFilter('isNumeric', [CoreRuntime\AppRuntime::class, 'isNumeric']),
            new TwigFilter('isEmail', [CoreRuntime\AppRuntime::class, 'isEmail']),
            new TwigFilter('isPhone', [CoreRuntime\AppRuntime::class, 'isPhone']),
            new TwigFilter('isDateTime', [CoreRuntime\AppRuntime::class, 'isDateTime']),
            new TwigFilter('hourBetweenTwoDates', [CoreRuntime\AppRuntime::class, 'hourBetweenTwoDates']),
            new TwigFilter('stringToDate', [CoreRuntime\AppRuntime::class, 'stringToDate']),
            new TwigFilter('strVal', [CoreRuntime\AppRuntime::class, 'strVal']),
            new TwigFilter('isUploadedFile', [CoreRuntime\AppRuntime::class, 'isUploadedFile']),
            new TwigFilter('isInt', [CoreRuntime\AppRuntime::class, 'isInt']),
            new TwigFilter('addDay', [CoreRuntime\AppRuntime::class, 'addDay']),
            new TwigFilter('addMinute', [CoreRuntime\AppRuntime::class, 'addMinute']),
            new TwigFilter('objectToArray', [CoreRuntime\AppRuntime::class, 'objectToArray']),
            new TwigFilter('entityValue', [CoreRuntime\AppRuntime::class, 'entityValue']),
            new TwigFilter('uniqId', [CoreRuntime\AppRuntime::class, 'uniqId']),
            new TwigFilter('charsId', [CoreRuntime\AppRuntime::class, 'charsId']),
            new TwigFilter('unset', [CoreRuntime\AppRuntime::class, 'unset']),
            new TwigFilter('unescape', [CoreRuntime\AppRuntime::class, 'unescape']),
            new TwigFilter('removeSession', [CoreRuntime\AppRuntime::class, 'removeSession']),
            new TwigFilter('url_decode', [CoreRuntime\AppRuntime::class, 'urlDecode']),
            new TwigFilter('serialize', [CoreRuntime\AppRuntime::class, 'serialize']),
            new TwigFilter('unserialize', [CoreRuntime\AppRuntime::class, 'unserialize']),
            new TwigFilter('implode', [CoreRuntime\AppRuntime::class, 'implode']),
            new TwigFilter('currentRequest', [CoreRuntime\AppRuntime::class, 'currentRequest']),
            new TwigFilter('masterRequest', [CoreRuntime\AppRuntime::class, 'masterRequest']),
            new TwigFilter('masterRequestGet', [CoreRuntime\AppRuntime::class, 'masterRequestGet']),
            new TwigFilter('replaceRequestParam', [CoreRuntime\AppRuntime::class, 'replaceRequestParam']),
            new TwigFilter('age', [CoreRuntime\AppRuntime::class, 'age']),
            new TwigFilter('percent', [CoreRuntime\AppRuntime::class, 'percent']),
            new TwigFilter('currentIP', [CoreRuntime\AppRuntime::class, 'currentIP']),
            new TwigFilter('entityTree', [CoreRuntime\AppRuntime::class, 'entityTree']),
            new TwigFilter('datetime', [CoreRuntime\AppRuntime::class, 'datetime']),
            new TwigFilter('countChars', [CoreRuntime\AppRuntime::class, 'countChars']),
            new TwigFilter('countCollection', [CoreRuntime\AppRuntime::class, 'countCollection']),
            new TwigFilter('inAdmin', [CoreRuntime\AppRuntime::class, 'inAdmin']),
            new TwigFilter('isUserBack', [CoreRuntime\AppRuntime::class, 'isUserBack']),
            new TwigFilter('isUserFront', [CoreRuntime\AppRuntime::class, 'isUserFront']),
            new TwigFilter('fileGetContent', [CoreRuntime\AppRuntime::class, 'fileGetContent']),
            new TwigFilter('fileGetContentURL', [CoreRuntime\AppRuntime::class, 'fileGetContentURL']),
            new TwigFilter('arrayKeyFirst', [CoreRuntime\AppRuntime::class, 'arrayKeyFirst']),
            new TwigFilter('removeBetween', [CoreRuntime\AppRuntime::class, 'removeBetween']),
            new TwigFilter('removeEmptyTags', [CoreRuntime\AppRuntime::class, 'removeEmptyTags']),
            new TwigFilter('getEnv', [CoreRuntime\AppRuntime::class, 'getEnv']),
            new TwigFilter('die', [CoreRuntime\AppRuntime::class, 'killRender']),
            new TwigFilter('javascriptFiles', [CoreRuntime\AssetRuntime::class, 'javascriptFiles']),
            new TwigFilter('csp_nonce', [CoreRuntime\NonceRuntime::class, 'getNonce']),
            new TwigFilter('profile_img', [CoreRuntime\SecurityRuntime::class, 'getProfileImg']),
            new TwigFilter('profile_addresses', [CoreRuntime\SecurityRuntime::class, 'getProfileAddresses']),
            new TwigFilter('online_users', [CoreRuntime\SecurityRuntime::class, 'getOnlineUsers']),
            new TwigFilter('granted', [CoreRuntime\SecurityRuntime::class, 'granted']),
            new TwigFilter('website', [CoreRuntime\WebsiteRuntime::class, 'website']),
            new TwigFilter('websiteId', [CoreRuntime\WebsiteRuntime::class, 'websiteId']),
            new TwigFilter('domain', [CoreRuntime\WebsiteRuntime::class, 'domain']),
            new TwigFilter('interface', [CoreRuntime\WebsiteRuntime::class, 'interface']),
            new TwigFilter('interfaceName', [CoreRuntime\WebsiteRuntime::class, 'interfaceName']),
            new TwigFilter('moduleActive', [CoreRuntime\WebsiteRuntime::class, 'moduleActive']),
            new TwigFilter('appColors', [CoreRuntime\WebsiteRuntime::class, 'appColors']),
            new TwigFilter('allWebsites', [CoreRuntime\WebsiteRuntime::class, 'allWebsites']),
            new TwigFilter('isMultiWebsite', [CoreRuntime\WebsiteRuntime::class, 'isMultiWebsite']),
        ];

        /** Translations */
        $translationFilters = [
            new TwigFilter('intl', [TranslationRuntime\i18nRuntime::class, 'intl']),
            new TwigFilter('intlAction', [TranslationRuntime\i18nRuntime::class, 'intlAction']),
            new TwigFilter('intlUrl', [TranslationRuntime\i18nRuntime::class, 'intlUrl']),
            new TwigFilter('intlMainUrl', [TranslationRuntime\i18nRuntime::class, 'intlMainUrl']),
            new TwigFilter('intlLink', [TranslationRuntime\i18nRuntime::class, 'intlLink']),
            new TwigFilter('intlMedia', [TranslationRuntime\i18nRuntime::class, 'intlMedia']),
            new TwigFilter('intlMedias', [TranslationRuntime\i18nRuntime::class, 'intlMedias']),
            new TwigFilter('findIntl', [TranslationRuntime\i18nRuntime::class, 'findIntl']),
            new TwigFilter('intlsModules', [TranslationRuntime\i18nRuntime::class, 'intlsModules']),
            new TwigFilter('intlsBlockTypes', [TranslationRuntime\i18nRuntime::class, 'intlsBlockTypes']),
            new TwigFilter('intlsWithContent', [TranslationRuntime\i18nRuntime::class, 'intlsWithContent']),
            new TwigFilter('readingDirection', [TranslationRuntime\IntlRuntime::class, 'readingDirection']),
            new TwigFilter('canonicalizeLocale', [TranslationRuntime\IntlRuntime::class, 'canonicalizeLocale']),
            new TwigFilter('countryNames', [TranslationRuntime\IntlRuntime::class, 'countryNames']),
            new TwigFilter('countryName', [TranslationRuntime\IntlRuntime::class, 'countryName']),
            new TwigFilter('languagesName', [TranslationRuntime\IntlRuntime::class, 'languagesName']),
            new TwigFilter('languageName', [TranslationRuntime\IntlRuntime::class, 'languageName']),
            new TwigFilter('currencyNames', [TranslationRuntime\IntlRuntime::class, 'currencyNames']),
            new TwigFilter('currencyName', [TranslationRuntime\IntlRuntime::class, 'currencyName']),
            new TwigFilter('currencySymbol', [TranslationRuntime\IntlRuntime::class, 'currencySymbol']),
            new TwigFilter('localeDayNameByDateTime', [TranslationRuntime\IntlRuntime::class, 'localeDayNameByDateTime']),
            new TwigFilter('localeMonthNameByDateTime', [TranslationRuntime\IntlRuntime::class, 'localeMonthNameByDateTime']),
            new TwigFilter('localeDayNameByEnglishName', [TranslationRuntime\IntlRuntime::class, 'localeDayNameByEnglishName']),
            new TwigFilter('localizedDate', [TranslationRuntime\IntlRuntime::class, 'localizedDate'], ['needs_environment' => true]),
            new TwigFilter('formatDate', [TranslationRuntime\IntlRuntime::class, 'formatDate']),
            new TwigFilter('transStats', [TranslationRuntime\StatsRuntime::class, 'transStats']),
            new TwigFilter('domainStats', [TranslationRuntime\StatsRuntime::class, 'domainStats']),
        ];

        return array_merge($adminFilters, $contentFilters, $coreFilters, $translationFilters);
    }

    public function getFunctions(): array
    {
        /** Admin */
        $adminFunctions = [
            new TwigFunction('symfonyVersion', [AdminRuntime\CoreRuntime::class, 'symfonyVersion']),
            new TwigFunction('phpversion', [AdminRuntime\CoreRuntime::class, 'phpversion']),
            new TwigFunction('blockTypesActionsGroups', [AdminRuntime\CoreRuntime::class, 'blockTypesActionsGroups']),
            new TwigFunction('indexAllowed', [AdminRuntime\CoreRuntime::class, 'indexAllowed']),
            new TwigFunction('seasonIcon', [AdminRuntime\CoreRuntime::class, 'seasonIcon']),
            new TwigFunction('logAlert', [AdminRuntime\CoreRuntime::class, 'logAlert']),
            new TwigFunction('methodInit', [AdminRuntime\CoreRuntime::class, 'methodInit']),
            new TwigFunction('buttonChecker', [AdminRuntime\CoreRuntime::class, 'buttonChecker']),
            new TwigFunction('buttonRoleChecker', [AdminRuntime\CoreRuntime::class, 'buttonRoleChecker']),
            new TwigFunction('blockFeatureName', [AdminRuntime\CoreRuntime::class, 'blockFeatureName']),
            new TwigFunction('blockTypesActive', [AdminRuntime\CoreRuntime::class, 'blockTypesActive']),
        ];

        /** Content */
        $contentFunctions = [
            new TwigFunction('breadcrumb', [BreadcrumbRuntime::class, 'breadcrumb']),
            new TwigFunction('indexPage', [BreadcrumbRuntime::class, 'indexPage']),
            new TwigFunction('browser', [ContentRuntime\BrowserRuntime::class, 'browser']),
            new TwigFunction('screen', [ContentRuntime\BrowserRuntime::class, 'screen']),
            new TwigFunction('isDesktop', [ContentRuntime\BrowserRuntime::class, 'isDesktop']),
            new TwigFunction('isTablet', [ContentRuntime\BrowserRuntime::class, 'isTablet']),
            new TwigFunction('isMobile', [ContentRuntime\BrowserRuntime::class, 'isMobile']),
            new TwigFunction('isFirefox', [ContentRuntime\BrowserRuntime::class, 'isFirefox']),
            new TwigFunction('isChrome', [ContentRuntime\BrowserRuntime::class, 'isChrome']),
            new TwigFunction('isSafari', [ContentRuntime\BrowserRuntime::class, 'isSafari']),
            new TwigFunction('isEdge', [ContentRuntime\BrowserRuntime::class, 'isEdge']),
            new TwigFunction('isIE', [ContentRuntime\BrowserRuntime::class, 'isIE']),
            new TwigFunction('isOpera', [ContentRuntime\BrowserRuntime::class, 'isOpera']),
            new TwigFunction('productData', [ContentRuntime\CatalogRuntime::class, 'productData']),
            new TwigFunction('allCatalogCategories', [ContentRuntime\CatalogRuntime::class, 'allCatalogCategories']),
            new TwigFunction('productInCart', [ContentRuntime\CatalogRuntime::class, 'productInCart']),
            new TwigFunction('productsInCart', [ContentRuntime\CatalogRuntime::class, 'productsInCart']),
            new TwigFunction('valueProductBySlugAndProduct', [ContentRuntime\CatalogRuntime::class, 'valueProductBySlugAndProduct']),
            new TwigFunction('featureValueBySlugs', [ContentRuntime\CatalogRuntime::class, 'featureValueBySlugs']),
            new TwigFunction('colors', [ContentRuntime\ColorRuntime::class, 'colors']),
            new TwigFunction('color', [ContentRuntime\ColorRuntime::class, 'color']),
            new TwigFunction('newZone', [ContentRuntime\ComponentRuntime::class, 'newZone']),
            new TwigFunction('newBlock', [ContentRuntime\ComponentRuntime::class, 'newBlock']),
            new TwigFunction('isComponentUser', [ContentRuntime\ComponentRuntime::class, 'isComponentUser']),
            new TwigFunction('lastRoute', [ContentRuntime\CoreRuntime::class, 'lastRoute']),
            new TwigFunction('jsonDecode', [ContentRuntime\CoreRuntime::class, 'jsonDecode']),
            new TwigFunction('email', [ContentRuntime\CoreRuntime::class, 'email']),
            new TwigFunction('phone', [ContentRuntime\CoreRuntime::class, 'phone']),
            new TwigFunction('address', [ContentRuntime\CoreRuntime::class, 'address']),
            new TwigFunction('mailToBody', [ContentRuntime\CoreRuntime::class, 'mailToBody']),
            new TwigFunction('urlize', [ContentRuntime\CoreRuntime::class, 'urlize']),
            new TwigFunction('removeHtmlAttrs', [ContentRuntime\CoreRuntime::class, 'removeHtmlAttrs']),
            new TwigFunction('encrypt', [ContentRuntime\CoreRuntime::class, 'encrypt']),
            new TwigFunction('decrypt', [ContentRuntime\CoreRuntime::class, 'decrypt']),
            new TwigFunction('uriInfos', [ContentRuntime\CoreRuntime::class, 'uriInfos']),
            new TwigFunction('truncate', [ContentRuntime\CoreRuntime::class, 'truncate']),
            new TwigFunction('centimeterToMeter', [ContentRuntime\CoreRuntime::class, 'centimeterToMeter']),
            new TwigFunction('minutesToHour', [ContentRuntime\CoreRuntime::class, 'minutesToHour']),
            new TwigFunction('firstIsVowel', [ContentRuntime\CoreRuntime::class, 'firstIsVowel']),
            new TwigFunction('htmlEntities', [ContentRuntime\CoreRuntime::class, 'htmlEntities']),
            new TwigFunction('intVal', [ContentRuntime\CoreRuntime::class, 'intVal']),
            new TwigFunction('shuffle', [ContentRuntime\CoreRuntime::class, 'shuffle']),
            new TwigFunction('fileInfo', [ContentRuntime\FileRuntime::class, 'fileInfo']),
            new TwigFunction('formatBytes', [ContentRuntime\FileRuntime::class, 'formatBytes']),
            new TwigFunction('convertToBytesSize', [ContentRuntime\FileRuntime::class, 'convertToBytesSize']),
            new TwigFunction('fileExist', [ContentRuntime\FileRuntime::class, 'fileExist']),
            new TwigFunction('jsRouting', [ContentRuntime\FileRuntime::class, 'jsRouting']),
            new TwigFunction('asGoogleFont', [ContentRuntime\FontsRuntime::class, 'asGoogleFont']),
            new TwigFunction('appAdminFonts', [ContentRuntime\FontsRuntime::class, 'appAdminFonts']),
            new TwigFunction('contactValues', [ContentRuntime\FormRuntime::class, 'contactValues']),
            new TwigFunction('indexGalleryCategories', [ContentRuntime\FormRuntime::class, 'indexGalleryCategories']),
            new TwigFunction('indexGalleryMedias', [ContentRuntime\FormRuntime::class, 'indexGalleryMedias']),
            new TwigFunction('cookies', [ContentRuntime\GdprRuntime::class, 'cookies']),
            new TwigFunction('cookie', [ContentRuntime\GdprRuntime::class, 'cookie']),
            new TwigFunction('iframe', [ContentRuntime\GdprRuntime::class, 'iframe']),
            new TwigFunction('addThis', [ContentRuntime\GdprRuntime::class, 'addThis']),
            new TwigFunction('tawkTo', [ContentRuntime\GdprRuntime::class, 'tawkTo']),
            new TwigFunction('gdprArguments', [ContentRuntime\GdprRuntime::class, 'gdprArguments']),
            new TwigFunction('markdown', [ContentRuntime\MarkdownRuntime::class, 'markdown']),
            new TwigFunction('extractMarkdownH1', [ContentRuntime\MarkdownRuntime::class, 'extractMarkdownH1']),
            new TwigFunction('icon', [ContentRuntime\IconRuntime::class, 'icon']),
            new TwigFunction('layoutRelations', [ContentRuntime\LayoutRuntime::class, 'layoutRelations']),
            new TwigFunction('cacheKey', [ContentRuntime\LayoutRuntime::class, 'cacheKey']),
            new TwigFunction('styleClass', [ContentRuntime\LayoutRuntime::class, 'styleClass']),
            new TwigFunction('renderBlock', [ContentRuntime\LayoutRuntime::class, 'renderBlock']),
            new TwigFunction('bodyClasses', [ContentRuntime\LayoutRuntime::class, 'bodyClasses']),
            new TwigFunction('zoneClasses', [ContentRuntime\LayoutRuntime::class, 'zoneClasses']),
            new TwigFunction('colClasses', [ContentRuntime\LayoutRuntime::class, 'colClasses']),
            new TwigFunction('blockClasses', [ContentRuntime\LayoutRuntime::class, 'blockClasses']),
            new TwigFunction('blockAlignment', [ContentRuntime\LayoutRuntime::class, 'blockAlignment']),
            new TwigFunction('elementOrders', [ContentRuntime\LayoutRuntime::class, 'elementOrders']),
            new TwigFunction('margins', [ContentRuntime\LayoutRuntime::class, 'margins']),
            new TwigFunction('paddings', [ContentRuntime\LayoutRuntime::class, 'paddings']),
            new TwigFunction('effectsAttrs', [ContentRuntime\LayoutRuntime::class, 'effectsAttrs']),
            new TwigFunction('mediasSizes', [ContentRuntime\LayoutRuntime::class, 'mediasSizes']),
            new TwigFunction('mainLayoutTitle', [ContentRuntime\LayoutRuntime::class, 'mainLayoutTitle']),
            new TwigFunction('layoutBlockType', [ContentRuntime\LayoutRuntime::class, 'layoutBlockType']),
            new TwigFunction('transitionsAttributes', [ContentRuntime\LayoutRuntime::class, 'transitionsAttributes']),
            new TwigFunction('transitionAttributes', [ContentRuntime\LayoutRuntime::class, 'transitionAttributes']),
            new TwigFunction('manifest', [ContentRuntime\ManifestRuntime::class, 'manifest']),
            new TwigFunction('mapPointsGroupByCategories', [ContentRuntime\MapRuntime::class, 'mapPointsGroupByCategories']),
            new TwigFunction('fonts', [ContentRuntime\MediaRuntime::class, 'fonts']),
            new TwigFunction('mediasSize', [ContentRuntime\MediaRuntime::class, 'mediasSize']),
            new TwigFunction('haveMainMedia', [ContentRuntime\MediaRuntime::class, 'haveMainMedia']),
            new TwigFunction('mainMedia', [ContentRuntime\MediaRuntime::class, 'mainMedia']),
            new TwigFunction('mediasIdsByPosition', [ContentRuntime\MediaRuntime::class, 'mediasIdsByPosition']),
            new TwigFunction('mediasByCategories', [ContentRuntime\MediaRuntime::class, 'mediasByCategories']),
            new TwigFunction('mediasWithFilename', [ContentRuntime\MediaRuntime::class, 'mediasWithFilename']),
            new TwigFunction('imgIsWhite', [ContentRuntime\MediaRuntime::class, 'imgIsWhite']),
            new TwigFunction('subNavigation', [ContentRuntime\MenuRuntime::class, 'subNavigation']),
            new TwigFunction('zonesNavigation', [ContentRuntime\MenuRuntime::class, 'zonesNavigation']),
            new TwigFunction('seo', [ContentRuntime\SeoRuntime::class, 'seo']),
            new TwigFunction('table', [ContentRuntime\TableRuntime::class, 'table']),
            new TwigFunction('fileIcon', [ContentRuntime\ThumbnailRuntime::class, 'fileIcon']),
            new TwigFunction('file', [ContentRuntime\ThumbnailRuntime::class, 'file']),
            new TwigFunction('thumb', [ContentRuntime\ThumbnailRuntime::class, 'thumb']),
            new TwigFunction('imgFilter', [ContentRuntime\ThumbnailRuntime::class, 'imgFilter']),
            new TwigFunction('mediaThumbs', [ContentRuntime\ThumbnailRuntime::class, 'mediaThumbs']),
            new TwigFunction('video', [ContentRuntime\VideoRuntime::class, 'video']),
        ];

        /** Core */
        $coreFunctions = [
            new TwigFunction('routeArgs', [CoreRuntime\AppRuntime::class, 'routeArgs']),
            new TwigFunction('find', [CoreRuntime\AppRuntime::class, 'find']),
            new TwigFunction('isDebug', [CoreRuntime\AppRuntime::class, 'isDebug']),
            new TwigFunction('routeExist', [CoreRuntime\AppRuntime::class, 'routeExist']),
            new TwigFunction('routeName', [CoreRuntime\AppRuntime::class, 'routeName']),
            new TwigFunction('getClass', [CoreRuntime\AppRuntime::class, 'getClass']),
            new TwigFunction('instanceof', [CoreRuntime\AppRuntime::class, 'instanceof']),
            new TwigFunction('isObject', [CoreRuntime\AppRuntime::class, 'isObject']),
            new TwigFunction('isArray', [CoreRuntime\AppRuntime::class, 'isArray']),
            new TwigFunction('isBool', [CoreRuntime\AppRuntime::class, 'isBool']),
            new TwigFunction('isNumeric', [CoreRuntime\AppRuntime::class, 'isNumeric']),
            new TwigFunction('isEmail', [CoreRuntime\AppRuntime::class, 'isEmail']),
            new TwigFunction('isPhone', [CoreRuntime\AppRuntime::class, 'isPhone']),
            new TwigFunction('isDateTime', [CoreRuntime\AppRuntime::class, 'isDateTime']),
            new TwigFunction('hourBetweenTwoDates', [CoreRuntime\AppRuntime::class, 'hourBetweenTwoDates']),
            new TwigFunction('stringToDate', [CoreRuntime\AppRuntime::class, 'stringToDate']),
            new TwigFunction('strVal', [CoreRuntime\AppRuntime::class, 'strVal']),
            new TwigFunction('isUploadedFile', [CoreRuntime\AppRuntime::class, 'isUploadedFile']),
            new TwigFunction('isInt', [CoreRuntime\AppRuntime::class, 'isInt']),
            new TwigFunction('addDay', [CoreRuntime\AppRuntime::class, 'addDay']),
            new TwigFunction('addMinute', [CoreRuntime\AppRuntime::class, 'addMinute']),
            new TwigFunction('objectToArray', [CoreRuntime\AppRuntime::class, 'objectToArray']),
            new TwigFunction('entityValue', [CoreRuntime\AppRuntime::class, 'entityValue']),
            new TwigFunction('uniqId', [CoreRuntime\AppRuntime::class, 'uniqId']),
            new TwigFunction('charsId', [CoreRuntime\AppRuntime::class, 'charsId']),
            new TwigFunction('unset', [CoreRuntime\AppRuntime::class, 'unset']),
            new TwigFunction('unescape', [CoreRuntime\AppRuntime::class, 'unescape']),
            new TwigFunction('removeSession', [CoreRuntime\AppRuntime::class, 'removeSession']),
            new TwigFunction('url_decode', [CoreRuntime\AppRuntime::class, 'urlDecode']),
            new TwigFunction('serialize', [CoreRuntime\AppRuntime::class, 'serialize']),
            new TwigFunction('unserialize', [CoreRuntime\AppRuntime::class, 'unserialize']),
            new TwigFunction('implode', [CoreRuntime\AppRuntime::class, 'implode']),
            new TwigFunction('currentRequest', [CoreRuntime\AppRuntime::class, 'currentRequest']),
            new TwigFunction('masterRequest', [CoreRuntime\AppRuntime::class, 'masterRequest']),
            new TwigFunction('masterRequestGet', [CoreRuntime\AppRuntime::class, 'masterRequestGet']),
            new TwigFunction('replaceRequestParam', [CoreRuntime\AppRuntime::class, 'replaceRequestParam']),
            new TwigFunction('age', [CoreRuntime\AppRuntime::class, 'age']),
            new TwigFunction('percent', [CoreRuntime\AppRuntime::class, 'percent']),
            new TwigFunction('currentIP', [CoreRuntime\AppRuntime::class, 'currentIP']),
            new TwigFunction('entityTree', [CoreRuntime\AppRuntime::class, 'entityTree']),
            new TwigFunction('datetime', [CoreRuntime\AppRuntime::class, 'datetime']),
            new TwigFunction('countChars', [CoreRuntime\AppRuntime::class, 'countChars']),
            new TwigFunction('countCollection', [CoreRuntime\AppRuntime::class, 'countCollection']),
            new TwigFunction('inAdmin', [CoreRuntime\AppRuntime::class, 'inAdmin']),
            new TwigFunction('isUserBack', [CoreRuntime\AppRuntime::class, 'isUserBack']),
            new TwigFunction('isUserFront', [CoreRuntime\AppRuntime::class, 'isUserFront']),
            new TwigFunction('fileGetContent', [CoreRuntime\AppRuntime::class, 'fileGetContent']),
            new TwigFunction('fileGetContentURL', [CoreRuntime\AppRuntime::class, 'fileGetContentURL']),
            new TwigFunction('arrayKeyFirst', [CoreRuntime\AppRuntime::class, 'arrayKeyFirst']),
            new TwigFunction('removeBetween', [CoreRuntime\AppRuntime::class, 'removeBetween']),
            new TwigFunction('removeEmptyTags', [CoreRuntime\AppRuntime::class, 'removeEmptyTags']),
            new TwigFunction('getEnv', [CoreRuntime\AppRuntime::class, 'getEnv']),
            new TwigFunction('die', [CoreRuntime\AppRuntime::class, 'killRender']),
            new TwigFunction('javascriptFiles', [CoreRuntime\AssetRuntime::class, 'javascriptFiles']),
            new TwigFunction('csp_nonce', [CoreRuntime\NonceRuntime::class, 'getNonce']),
            new TwigFunction('profile_img', [CoreRuntime\SecurityRuntime::class, 'getProfileImg']),
            new TwigFunction('profile_addresses', [CoreRuntime\SecurityRuntime::class, 'getProfileAddresses']),
            new TwigFunction('online_users', [CoreRuntime\SecurityRuntime::class, 'getOnlineUsers']),
            new TwigFunction('granted', [CoreRuntime\SecurityRuntime::class, 'granted']),
            new TwigFunction('website', [CoreRuntime\WebsiteRuntime::class, 'website']),
            new TwigFunction('websiteId', [CoreRuntime\WebsiteRuntime::class, 'websiteId']),
            new TwigFunction('domain', [CoreRuntime\WebsiteRuntime::class, 'domain']),
            new TwigFunction('interface', [CoreRuntime\WebsiteRuntime::class, 'interface']),
            new TwigFunction('interfaceName', [CoreRuntime\WebsiteRuntime::class, 'interfaceName']),
            new TwigFunction('moduleActive', [CoreRuntime\WebsiteRuntime::class, 'moduleActive']),
            new TwigFunction('appColors', [CoreRuntime\WebsiteRuntime::class, 'appColors']),
            new TwigFunction('allWebsites', [CoreRuntime\WebsiteRuntime::class, 'allWebsites']),
            new TwigFunction('isMultiWebsite', [CoreRuntime\WebsiteRuntime::class, 'isMultiWebsite']),
        ];

        /** Translations */
        $translationFunctions = [
            new TwigFunction('intl', [TranslationRuntime\i18nRuntime::class, 'intl']),
            new TwigFunction('intlAction', [TranslationRuntime\i18nRuntime::class, 'intlAction']),
            new TwigFunction('intlUrl', [TranslationRuntime\i18nRuntime::class, 'intlUrl']),
            new TwigFunction('intlMainUrl', [TranslationRuntime\i18nRuntime::class, 'intlMainUrl']),
            new TwigFunction('intlLink', [TranslationRuntime\i18nRuntime::class, 'intlLink']),
            new TwigFunction('intlMedia', [TranslationRuntime\i18nRuntime::class, 'intlMedia']),
            new TwigFunction('intlMedias', [TranslationRuntime\i18nRuntime::class, 'intlMedias']),
            new TwigFunction('findIntl', [TranslationRuntime\i18nRuntime::class, 'findIntl']),
            new TwigFunction('intlsModules', [TranslationRuntime\i18nRuntime::class, 'intlsModules']),
            new TwigFunction('intlsBlockTypes', [TranslationRuntime\i18nRuntime::class, 'intlsBlockTypes']),
            new TwigFunction('intlsWithContent', [TranslationRuntime\i18nRuntime::class, 'intlsWithContent']),
            new TwigFunction('readingDirection', [TranslationRuntime\IntlRuntime::class, 'readingDirection']),
            new TwigFunction('canonicalizeLocale', [TranslationRuntime\IntlRuntime::class, 'canonicalizeLocale']),
            new TwigFunction('countryNames', [TranslationRuntime\IntlRuntime::class, 'countryNames']),
            new TwigFunction('countryName', [TranslationRuntime\IntlRuntime::class, 'countryName']),
            new TwigFunction('languagesName', [TranslationRuntime\IntlRuntime::class, 'languagesName']),
            new TwigFunction('languageName', [TranslationRuntime\IntlRuntime::class, 'languageName']),
            new TwigFunction('currencyNames', [TranslationRuntime\IntlRuntime::class, 'currencyNames']),
            new TwigFunction('currencyName', [TranslationRuntime\IntlRuntime::class, 'currencyName']),
            new TwigFunction('currencySymbol', [TranslationRuntime\IntlRuntime::class, 'currencySymbol']),
            new TwigFunction('localeDayNameByDateTime', [TranslationRuntime\IntlRuntime::class, 'localeDayNameByDateTime']),
            new TwigFunction('localeMonthNameByDateTime', [TranslationRuntime\IntlRuntime::class, 'localeMonthNameByDateTime']),
            new TwigFunction('localeDayNameByEnglishName', [TranslationRuntime\IntlRuntime::class, 'localeDayNameByEnglishName']),
            new TwigFunction('localizedDate', [TranslationRuntime\IntlRuntime::class, 'localizedDate'], ['needs_environment' => true]),
            new TwigFunction('formatDate', [TranslationRuntime\IntlRuntime::class, 'formatDate']),
            new TwigFunction('transStats', [TranslationRuntime\StatsRuntime::class, 'transStats']),
            new TwigFunction('domainStats', [TranslationRuntime\StatsRuntime::class, 'domainStats']),
        ];

        return array_merge($adminFunctions, $contentFunctions, $coreFunctions, $translationFunctions);
    }
}
